package main

import (
	_ "github.com/aerosystems/project-service/docs" // docs are generated by Swag CLI, you have to import it.
	"github.com/aerosystems/project-service/internal/models"
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

func (app *Config) NewRouter() *echo.Echo {
	e := echo.New()

	// Private routes Basic Auth
	docsGroup := e.Group("/docs")
	docsGroup.Use(app.basicAuthMiddleware.BasicAuthMiddleware)
	docsGroup.GET("/*", echoSwagger.WrapHandler)

	// Private routes X-Api-Key
	e.GET("/v1/token/validate", app.baseHandler.ValidateToken)

	// Private routes OAuth 2.0: check roles [customer, staff]. Auth implemented on API Gateway
	e.GET("/v1/projects", app.baseHandler.GetProjectList, app.oauthMiddleware.AuthTokenMiddleware(models.CustomerRole, models.StaffRole))
	e.GET("/v1/projects/:projectId", app.baseHandler.GetProject, app.oauthMiddleware.AuthTokenMiddleware(models.CustomerRole, models.StaffRole))

	// Private routes OAuth 2.0: check roles [staff]. Auth implemented on API Gateway
	e.POST("/v1/projects", app.baseHandler.ProjectCreate, app.oauthMiddleware.AuthTokenMiddleware(models.StaffRole))
	e.PATCH("/v1/projects/:projectId", app.baseHandler.ProjectUpdate, app.oauthMiddleware.AuthTokenMiddleware(models.StaffRole))
	e.DELETE("/v1/projects/:projectId", app.baseHandler.ProjectDelete, app.oauthMiddleware.AuthTokenMiddleware(models.StaffRole))

	return e
}
