basePath: /
host: localhost:8082
info:
  contact:
    name: Artem Kostenko
    url: https://github.com/aerosystems
  description: A part of microservice infrastructure, who responsible for managing
    user Projects
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Project Service
  version: 1.0.5
paths: {}
securityDefinitions:
  BearerAuth:
    description: Should contain Access JWT Token, with the Bearer started
    in: header
    name: Authorization
    type: apiKey
  X-API-KEY:
    description: Should contain Token, digits and letters, 64 symbols length
    in: header
    name: X-API-KEY
    type: apiKey
swagger: "2.0"
